apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot-demo
  name: springboot-demo
  namespace: springboot-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-demo
    spec:
      containers:
      - image: dockernvkk/springbootapp:latest
        name: springboot-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  namespace: springboot-apps
spec:
  ports:
  - name: service
    port: 8180
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}