server:
    port: 8080
    
management.endpoints.web.exposure.include: '*'
management.security.enabled: false
management.metrics.enable.jvm: true

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
# management:
#   endpoints:
#     enabled-by-default: false
#     web:
#       exposure:
#         include: "*"
#         exclude: "env,beans"
#   endpoint:
#     info:
#       enabled: true
      
